"""Contains the base class for :class:`TransactionCtrl`."""
import ioc
from sq.ctrl import EndpointCtrl

class BaseTransactionCtrl(EndpointCtrl):
    """Generated by SG to serve as an abstract base class for:

        idin.app.ctrl.TransactionCtrl

    This class encapsulates external dependencies (such as the inversion-of-control
    requirements) and specifies the interface for the concrete implementation.
    """
    idin = ioc.class_property('IdinService')

    async def post(self, request, *args, **kwargs):
        """This method specifies the signature for :meth:`TransactionCtrl.post()`
        and should be implemented in the following file:

            ./idin/ctrl/transaction/impl.py
        """
        raise NotImplementedError("Subclasses must override this method.")

    async def get(self, request, *args, **kwargs):
        """This method specifies the signature for :meth:`TransactionCtrl.get()`
        and should be implemented in the following file:

            ./idin/ctrl/transaction/impl.py
        """
        raise NotImplementedError("Subclasses must override this method.")


#pylint: skip-file
# !!! SG MANAGED FILE -- DO NOT EDIT -- VERSION:  !!!
