"""initial revision

Revision ID: 44bce379d3ad
Revises: 
Create Date: 2018-09-16 00:46:25.093708

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = '44bce379d3ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('txid', sa.String(), nullable=False),
    sa.Column('created', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ec', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('txid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
