"""Add bin column

Revision ID: e6f39dcf7b0c
Revises: 3bea38dae933
Create Date: 2018-09-16 14:47:47.525909

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = 'e6f39dcf7b0c'
down_revision = '3bea38dae933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
