---
relations:
- relname: transactions
  classname: Transaction
  description: >
    Maintains information about iDIN transactions.
  columns:
  - name: txid
    type: string
    primary_key: true
    description: >
      Transaction ID as specified by the intermediary.
  - name: created
    type: int64
    description: >
      The date/time at which the transaction was created, in milliseconds
      since the UNIX epoch.
  - name: status
    type: string
    default:
      type: literal
      value: "'open'"
    description: >
      Current status of the transaction, may be one of ``open``,
      ``success``, ``cancelled``, ``failure`` or ``expired``.
  - name: ec
    type: string
    max_length: 40
    description: >
      Entrance code to be included in the response from the iDIN
      acquirer.
  - name: ref
    type: string
    description: >
      Reference at the intermediary for accounting purposes.
