---
relations:
- relname: transactions
  classname: Transaction
  description: >
    Maintains information about iDIN transactions.
  columns:
  - name: txid
    type: string
    primary_key: true
    description: >
      Transaction ID as specified by the intermediary.
  - name: created
    type: int64
    description: >
      The date/time at which the transaction was created, in milliseconds
      since the UNIX epoch.
  - name: status
    type: string
    default:
      type: literal
      value: "'open'"
    description: >
      Current status of the transaction, may be one of ``open``,
      ``success``, ``cancelled``, ``failure`` or ``expired``.
  - name: ec
    type: string
    max_length: 40
    description: >
      Entrance code to be included in the response from the iDIN
      acquirer.
  - name: ref
    type: string
    description: >
      Reference at the intermediary for accounting purposes.

- relname: results
  classname: Result
  description: >
    Maintains the results of successful iDIN transactions.
  columns:
  - name: txid
    ref: transactions.txid
    primary_key: true
    description: >
      Identifies the transaction of this result.
  - name: issuer_id
    type: string
    description: >
      Identifies the issuer.
  - name: bin
    type: string
    description: >
      The Bank Identification Number (BIN) identifying the customer,
      as returned by the iDIN issuer.
  - name: data
    type: string
    description: >
      The data yielded by the iDIN transaction, serialized as JSON with sorted
      keys.
  - name: checksum
    type: binary
    unique: true
    description: >
      A SHA-256 hash of the transaction identifier and the result.
  - name: retrieved
    type: int64
    description: >
      The date/time at which the result was retrieved, in milliseconds since the UNIX
      epoch.
  - name: timestamped
    type: boolean
    default:
      type: literal
      value: "False"
    description: >
      Specifies if a secure time stamp is requested and persisted for the
      checksum of this result.
